### ISSUE TITLE
Volume control not showing up for non Bandcamp URLs

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [ubercow/bandcamp_volume#13] opened 2016-12-20 07:20 UTC
Like if a website is directing towards their Bandcamp page, if the URL doesn't have "bandcamp.com" in it.. the volume control doesn't show up

An example page.. http://ephixa.com/track/kirby-gourmet-race-remix

**Comment by dmland** [comment] 2016-12-28 18:06
Looks like a duplicate of #2

**Comment by helloitszak** [comment] 2017-01-04 01:18
Hey @SaiyanOfDarkness,

Unfortunately due to a Chrome's security, which only lets my plugin access sites that are on `bandcamp.com`. There is no way for Chrome to tell which website is a "bandcamp site" and which website is just a "random site on the internet".

The only fix for this is to have Bandcamp Volume read the contents of every page on Chrome, which I am unwilling to do for security and privacy reasons. It's very unlikely that this will ever be possible unless something changes with Chrome.

Zak

**Closed as completed by helloitszak** 2017-01-04 01:18 UTC
